package main

// Code generated by vugu via vugugen. Please regenerate instead of editing or add additional code in a separate file. DO NOT EDIT.

import "fmt"
import "reflect"
import "github.com/vugu/vjson"
import "github.com/vugu/vugu"
import js "github.com/vugu/vugu/js"


type User struct {
    firstname   string
    lastname    string
    username    string
    password    string
    email       string
    gender      string
}
func (c *User) Build(vgin *vugu.BuildIn) (vgout *vugu.BuildOut) {
    
    vgout = &vugu.BuildOut{}
    
    var vgiterkey interface{}
    _ = vgiterkey
    var vgn *vugu.VGNode
vgn = &vugu.VGNode{Type:vugu.VGNodeType(3),Namespace:"",Data:"div",Attr:[]vugu.VGAttribute{vugu.VGAttribute{Namespace:"", Key:"class", Val:"profile_box"}}}
vgout.Out = append(vgout.Out, vgn) // root for output
vgn.AddAttrInterface("class",gender)
{
vgparent := vgn; _ = vgparent
vgn = &vugu.VGNode{Type:vugu.VGNodeType(1),Data:"\n    "}
vgparent.AppendChild(vgn)
vgn = &vugu.VGNode{Type:vugu.VGNodeType(3),Namespace:"",Data:"h3",Attr:[]vugu.VGAttribute(nil)}
vgparent.AppendChild(vgn)
vgn.SetInnerHTML(c.firstname c.lastname)
vgn = &vugu.VGNode{Type:vugu.VGNodeType(1),Data:"\n    "}
vgparent.AppendChild(vgn)
vgn = &vugu.VGNode{Type:vugu.VGNodeType(3),Namespace:"",Data:"p",Attr:[]vugu.VGAttribute(nil)}
vgparent.AppendChild(vgn)
vgn.SetInnerHTML(Username c.username)
vgn = &vugu.VGNode{Type:vugu.VGNodeType(1),Data:"\n"}
vgparent.AppendChild(vgn)
}
    return vgout
}

// 'fix' unused imports
var _ fmt.Stringer
var _ reflect.Type
var _ vjson.RawMessage
var _ js.Value

